INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1065', 'ABDULLAH GÜL ÜNİVERSİTESİ  ', '38');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1104', 'ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ  ', '1');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1002', 'ADIYAMAN ÜNİVERSİTESİ  ', '2');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1004', 'AFYON KOCATEPE ÜNİVERSİTESİ  ', '3');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1126', 'AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ  ', '3');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1005', 'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ  ', '4');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1007', 'AKDENİZ ÜNİVERSİTESİ  ', '7');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1008', 'AKSARAY ÜNİVERSİTESİ  ', '68');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1105', 'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ  ', '7');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1009', 'AMASYA ÜNİVERSİTESİ  ', '5');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1010', 'ANADOLU ÜNİVERSİTESİ  ', '26');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1117', 'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1109', 'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1011', 'ANKARA ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1100', 'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1012', 'ARDAHAN ÜNİVERSİTESİ  ', '75');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1013', 'ARTVİN ÇORUH ÜNİVERSİTESİ  ', '8');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1014', 'ATATÜRK ÜNİVERSİTESİ  ', '25');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1003', 'AYDIN ADNAN MENDERES ÜNİVERSİTESİ  ', '9');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1015', 'BALIKESİR ÜNİVERSİTESİ  ', '10');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1106', 'BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ  ', '10');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1016', 'BARTIN ÜNİVERSİTESİ  ', '74');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1017', 'BATMAN ÜNİVERSİTESİ  ', '72');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1018', 'BAYBURT ÜNİVERSİTESİ  ', '69');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1019', 'BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ  ', '11');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1020', 'BİNGÖL ÜNİVERSİTESİ  ', '12');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1021', 'BİTLİS EREN ÜNİVERSİTESİ  ', '13');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1022', 'BOĞAZİÇİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1001', 'BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ  ', '14');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1073', 'BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ  ', '15');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1024', 'BURSA TEKNİK ÜNİVERSİTESİ  ', '16');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1097', 'BURSA ULUDAĞ ÜNİVERSİTESİ  ', '16');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1027', 'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ  ', '17');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1028', 'ÇANKIRI KARATEKİN ÜNİVERSİTESİ  ', '18');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1029', 'ÇUKUROVA ÜNİVERSİTESİ  ', '1');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1030', 'DİCLE ÜNİVERSİTESİ  ', '21');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1031', 'DOKUZ EYLÜL ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1033', 'DÜZCE ÜNİVERSİTESİ  ', '81');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1034', 'EGE ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1035', 'ERCİYES ÜNİVERSİTESİ  ', '38');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1036', 'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ  ', '24');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1037', 'ERZURUM TEKNİK ÜNİVERSİTESİ  ', '25');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1038', 'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ  ', '26');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1124', 'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ  ', '26');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1039', 'FIRAT ÜNİVERSİTESİ  ', '23');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1040', 'GALATASARAY ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1041', 'GAZİ ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1112', 'GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ  ', '27');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1042', 'GAZİANTEP ÜNİVERSİTESİ  ', '27');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1044', 'GEBZE TEKNİK ÜNİVERSİTESİ  ', '41');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1045', 'GİRESUN ÜNİVERSİTESİ  ', '28');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1047', 'GÜMÜŞHANE ÜNİVERSİTESİ  ', '29');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1048', 'HACETTEPE ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1049', 'HAKKARİ ÜNİVERSİTESİ  ', '30');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1050', 'HARRAN ÜNİVERSİTESİ  ', '63');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1077', 'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ  ', '31');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1051', 'HİTİT ÜNİVERSİTESİ  ', '19');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1052', 'IĞDIR ÜNİVERSİTESİ  ', '76');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1125', 'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ  ', '32');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1053', 'İNÖNÜ ÜNİVERSİTESİ  ', '44');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1107', 'İSKENDERUN TEKNİK ÜNİVERSİTESİ  ', '31');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1054', 'İSTANBUL MEDENİYET ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1055', 'İSTANBUL TEKNİK ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1056', 'İSTANBUL ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1116', 'İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1129', 'İZMİR BAKIRÇAY ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1111', 'İZMİR DEMOKRASİ ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1057', 'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1058', 'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1059', 'KAFKAS ÜNİVERSİTESİ  ', '36');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1122', 'KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ  ', '46');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1060', 'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ  ', '46');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1061', 'KARABÜK ÜNİVERSİTESİ  ', '78');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1062', 'KARADENİZ TEKNİK ÜNİVERSİTESİ  ', '61');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1063', 'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ  ', '70');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1064', 'KASTAMONU ÜNİVERSİTESİ  ', '37');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1123', 'KAYSERİ ÜNİVERSİTESİ  ', '38');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1066', 'KIRIKKALE ÜNİVERSİTESİ  ', '71');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1067', 'KIRKLARELİ ÜNİVERSİTESİ  ', '39');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1006', 'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ  ', '40');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1068', 'KİLİS 7 ARALIK ÜNİVERSİTESİ  ', '79');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1069', 'KOCAELİ ÜNİVERSİTESİ  ', '41');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1113', 'KONYA TEKNİK ÜNİVERSİTESİ  ', '42');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1032', 'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ  ', '43');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1114', 'KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ  ', '43');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1115', 'MALATYA TURGUT ÖZAL ÜNİVERSİTESİ  ', '44');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1025', 'MANİSA CELÂL BAYAR ÜNİVERSİTESİ  ', '45');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1071', 'MARDİN ARTUKLU ÜNİVERSİTESİ  ', '47');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1072', 'MARMARA ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1074', 'MERSİN ÜNİVERSİTESİ  ', '33');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1075', 'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1076', 'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ  ', '48');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1095', 'MUNZUR ÜNİVERSİTESİ  ', '62');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1078', 'MUŞ ALPARSLAN ÜNİVERSİTESİ  ', '49');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1070', 'NECMETTİN ERBAKAN ÜNİVERSİTESİ  ', '42');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1080', 'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ  ', '50');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1081', 'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ  ', '51');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1082', 'ONDOKUZ MAYIS ÜNİVERSİTESİ  ', '55');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1083', 'ORDU ÜNİVERSİTESİ  ', '52');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1084', 'ORTA DOĞU TEKNİK ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1085', 'OSMANİYE KORKUT ATA ÜNİVERSİTESİ  ', '80');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1086', 'PAMUKKALE ÜNİVERSİTESİ  ', '20');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1087', 'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ  ', '53');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1110', 'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1118', 'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ  ', '54');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1088', 'SAKARYA ÜNİVERSİTESİ  ', '54');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1127', 'SAMSUN ÜNİVERSİTESİ  ', '55');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1089', 'SELÇUK ÜNİVERSİTESİ  ', '42');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1090', 'SİİRT ÜNİVERSİTESİ  ', '56');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1091', 'SİNOP ÜNİVERSİTESİ  ', '57');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1119', 'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ  ', '58');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1026', 'SİVAS CUMHURİYET ÜNİVERSİTESİ  ', '58');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1092', 'SÜLEYMAN DEMİREL ÜNİVERSİTESİ  ', '32');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1093', 'ŞIRNAK ÜNİVERSİTESİ  ', '73');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1120', 'TARSUS ÜNİVERSİTESİ  ', '33');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1079', 'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ  ', '59');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1043', 'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ  ', '60');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1121', 'TRABZON ÜNİVERSİTESİ  ', '61');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1094', 'TRAKYA ÜNİVERSİTESİ  ', '22');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1096', 'TÜRK-ALMAN ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1098', 'UŞAK ÜNİVERSİTESİ  ', '64');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1102', 'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ  ', '65');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1099', 'YALOVA ÜNİVERSİTESİ  ', '77');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1101', 'YILDIZ TEKNİK ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1023', 'YOZGAT BOZOK ÜNİVERSİTESİ  ', '66');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('1103', 'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ  ', '67');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4039', 'HOCA AHMET YESEVİ ULUSLARARASI TÜRK-KAZAK ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4052', 'KIRGIZİSTAN-TÜRKİYE MANAS ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2001', 'ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2101', 'ALANYA ÜNİVERSİTESİ  ', '7');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2029', 'ALTINBAŞ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2095', 'ANKARA BİLİM ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2092', 'ANKARA MEDİPOL ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2102', 'ANTALYA BELEK ÜNİVERSİTESİ  ', '7');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2064', 'ANTALYA BİLİM ÜNİVERSİTESİ  ', '7');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2002', 'ATILIM ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2003', 'AVRASYA ÜNİVERSİTESİ  ', '61');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2005', 'BAHÇEŞEHİR ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2006', 'BAŞKENT ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2008', 'BEYKOZ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2009', 'BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2076', 'BİRUNİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2010', 'ÇAĞ ÜNİVERSİTESİ  ', '33');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2011', 'ÇANKAYA ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2026', 'DEMİROĞLU BİLİM ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2012', 'DOĞUŞ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2014', 'FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2090', 'FENERBAHÇE ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2019', 'HALİÇ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2016', 'HASAN KALYONCU ÜNİVERSİTESİ  ', '27');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2020', 'IŞIK ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2086', 'İBN HALDUN ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2021', 'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2022', 'İSTANBUL 29 MAYIS ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2023', 'İSTANBUL AREL ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2093', 'İSTANBUL ATLAS ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2024', 'İSTANBUL AYDIN ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2103', 'İSTANBUL BEYKENT ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2025', 'İSTANBUL BİLGİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2075', 'İSTANBUL ESENYURT ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2098', 'İSTANBUL GALATA ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2017', 'İSTANBUL GEDİK ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2027', 'İSTANBUL GELİŞİM ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2087', 'İSTANBUL KENT ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2030', 'İSTANBUL KÜLTÜR ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2031', 'İSTANBUL MEDİPOL ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2104', 'İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2047', 'İSTANBUL OKAN ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2081', 'İSTANBUL RUMELİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2032', 'İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2094', 'İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2034', 'İSTANBUL TİCARET ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2050', 'İSTANBUL TOPKAPI ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2062', 'İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2084', 'İSTİNYE ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2035', 'İZMİR EKONOMİ ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2096', 'İZMİR TINAZTEPE ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2037', 'KADİR HAS ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2038', 'KAPADOKYA ÜNİVERSİTESİ  ', '50');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2097', 'KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ  ', '41');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2039', 'KOÇ ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2083', 'KONYA GIDA VE TARIM ÜNİVERSİTESİ  ', '42');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2040', 'KTO KARATAY ÜNİVERSİTESİ  ', '42');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2088', 'LOKMAN HEKİM ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2041', 'MALTEPE ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2072', 'MEF ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2100', 'MUDANYA ÜNİVERSİTESİ  ', '16');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2046', 'NUH NACİ YAZGAN ÜNİVERSİTESİ  ', '38');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2091', 'OSTİM TEKNİK ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2048', 'ÖZYEĞİN ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2049', 'PİRİ REİS ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2051', 'SABANCI ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2077', 'SANKO ÜNİVERSİTESİ  ', '27');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2067', 'TED ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2054', 'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2055', 'TOROS ÜNİVERSİTESİ  ', '33');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2057', 'TÜRK HAVA KURUMU ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2058', 'UFUK ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2065', 'ÜSKÜDAR ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2060', 'YAŞAR ÜNİVERSİTESİ  ', '35');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2061', 'YEDİTEPE ÜNİVERSİTESİ  ', '34');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('2079', 'YÜKSEK İHTİSAS ÜNİVERSİTESİ  ', '6');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3014', 'ADA KENT ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3006', 'AKDENİZ KARPAZ ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3016', 'ARKIN YARATICI SANATLAR VE TASARIM ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3017', 'BAHÇEŞEHİR KIBRIS ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3001', 'DOĞU AKDENİZ ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3002', 'GİRNE AMERİKAN ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3007', 'GİRNE ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3009', 'KIBRIS AMERİKAN ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3015', 'KIBRIS BATI ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3008', 'KIBRIS İLİM ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3012', 'KIBRIS SAĞLIK VE TOPLUM BİLİMLERİ ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3003', 'LEFKE AVRUPA ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3018', 'RAUF DENKTAŞ ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3013', 'ULUSLARARASI FİNAL ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3004', 'ULUSLARARASI KIBRIS ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('3005', 'YAKIN DOĞU ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4011', 'AZERBAYCAN DEVLET PEDAGOJİ ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4013', 'AZERBAYCAN DİLLER ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4017', 'AZERBAYCAN TIP ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4020', 'BAKÜ DEVLET ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4088', 'ULUSLARARASI SARAYBOSNA ÜNİVERSİTESİ  ', '82');
INSERT INTO tableName (uni_id, uni_name, city_id) VALUES ('4096', 'ULUSLARARASI BALKAN ÜNİVERSİTESİ  ', '82');
