INSERT INTO uni (id,name,location,type,url) VALUES  ( 1 , 'ABDULLAH GÜL ÜNİVERSİTESİ' , 'Kayseri' , 'Devlet' , 'http://www.agu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 2 , 'ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.acibadem.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 3 , 'ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ' , 'Adana' , 'Devlet' , 'http://www.atu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 4 , 'ADIYAMAN ÜNİVERSİTESİ' , 'Adıyaman' , 'Devlet' , 'http://www.adiyaman.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 5 , 'AFYON KOCATEPE ÜNİVERSİTESİ' , 'Afyonkarahisar' , 'Devlet' , 'http://www.aku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 6 , 'AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ' , 'Afyonkarahisar' , 'Devlet' , 'www.afsu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 7 , 'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ' , 'Ağrı' , 'Devlet' , 'http://www.agri.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 8 , 'AKDENİZ ÜNİVERSİTESİ' , 'Antalya' , 'Devlet' , 'http://www.akdeniz.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 9 , 'AKSARAY ÜNİVERSİTESİ' , 'Aksaray' , 'Devlet' , 'www.aksaray.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 10 , 'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ' , 'Antalya' , 'Devlet' , 'http://www.alanya.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 11 , 'ALANYA ÜNİVERSİTESİ' , 'Antalya' , 'Vakıf' , 'http://www.alanyauniversity.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 12 , 'ALTINBAŞ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.altinbas.edu.tr/tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 13 , 'AMASYA ÜNİVERSİTESİ' , 'Amasya' , 'Devlet' , 'http://www.amasya.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 14 , 'ANADOLU ÜNİVERSİTESİ' , 'Eskişehir' , 'Devlet' , 'http://www.anadolu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 15 , 'ANKARA BİLİM ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.ankarabilim.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 16 , 'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'https://hacibayram.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 17 , 'ANKARA MEDİPOL ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.ankaramedipol.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 18 , 'ANKARA MÜZİK VE GÜZEL SANATLAR ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://www.mgu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 19 , 'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://www.asbu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 20 , 'ANKARA ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://www.ankara.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 21 , 'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'www.aybu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 22 , 'ANTALYA BELEK ÜNİVERSİTESİ' , 'Antalya' , 'Vakıf' , 'www.belek.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 23 , 'ANTALYA BİLİM ÜNİVERSİTESİ' , 'Antalya' , 'Vakıf' , 'http://www.antalya.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 24 , 'ARDAHAN ÜNİVERSİTESİ' , 'Ardahan' , 'Devlet' , 'http://www.ardahan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 25 , 'ARTVİN ÇORUH ÜNİVERSİTESİ' , 'Artvin' , 'Devlet' , 'http://www.artvin.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 26 , 'ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU' , 'İstanbul' , 'Vakıf' , 'http://www.adiguzel.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 27 , 'ATATÜRK ÜNİVERSİTESİ' , 'Erzurum' , 'Devlet' , 'http://www.atauni.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 28 , 'ATILIM ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.atilim.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 29 , 'AVRASYA ÜNİVERSİTESİ' , 'Trabzon' , 'Vakıf' , 'http://www.avrasya.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 30 , 'AYDIN ADNAN MENDERES ÜNİVERSİTESİ' , 'Aydın' , 'Devlet' , 'http://www.adu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 31 , 'BAHÇEŞEHİR ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.bahcesehir.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 32 , 'BALIKESİR ÜNİVERSİTESİ' , 'Balıkesir' , 'Devlet' , 'http://www.balikesir.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 33 , 'BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ' , 'Balıkesir' , 'Devlet' , 'http://www.bandirma.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 34 , 'BARTIN ÜNİVERSİTESİ' , 'Bartın' , 'Devlet' , 'http://www.bartin.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 35 , 'BAŞKENT ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.baskent.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 36 , 'BATMAN ÜNİVERSİTESİ' , 'Batman' , 'Devlet' , 'http://www.batman.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 37 , 'BAYBURT ÜNİVERSİTESİ' , 'Bayburt' , 'Devlet' , 'https://bayburt.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 38 , 'BEYKOZ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.beykoz.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 39 , 'BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.bezmialem.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 40 , 'BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ' , 'Bilecik' , 'Devlet' , 'http://www.bilecik.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 41 , 'BİNGÖL ÜNİVERSİTESİ' , 'Bingöl' , 'Devlet' , 'http://www.bingol.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 42 , 'BİRUNİ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.biruni.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 43 , 'BİTLİS EREN ÜNİVERSİTESİ' , 'Bitlis' , 'Devlet' , 'www.beu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 44 , 'BOĞAZİÇİ ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.boun.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 45 , 'BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ' , 'Bolu' , 'Devlet' , 'http://www.ibu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 46 , 'BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ' , 'Burdur' , 'Devlet' , 'http://www.mehmetakif.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 47 , 'BURSA TEKNİK ÜNİVERSİTESİ' , 'Bursa' , 'Devlet' , 'http://btu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 48 , 'BURSA ULUDAĞ ÜNİVERSİTESİ' , 'Bursa' , 'Devlet' , 'http://www.uludag.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 49 , 'ÇAĞ ÜNİVERSİTESİ' , 'Mersin' , 'Vakıf' , 'http://www.cag.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 50 , 'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ' , 'Çanakkale' , 'Devlet' , 'www.comu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 51 , 'ÇANKAYA ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.cankaya.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 52 , 'ÇANKIRI KARATEKİN ÜNİVERSİTESİ' , 'Çankırı' , 'Devlet' , 'www.karatekin.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 53 , 'ÇUKUROVA ÜNİVERSİTESİ' , 'Adana' , 'Devlet' , 'www.cu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 54 , 'DEMİROĞLU BİLİM ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.demiroglu.bilim.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 55 , 'DİCLE ÜNİVERSİTESİ' , 'Diyarbakır' , 'Devlet' , 'www.dicle.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 56 , 'DOĞUŞ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.dogus.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 57 , 'DOKUZ EYLÜL ÜNİVERSİTESİ' , 'İzmir' , 'Devlet' , 'http://www.deu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 58 , 'DÜZCE ÜNİVERSİTESİ' , 'Düzce' , 'Devlet' , 'http://www.duzce.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 59 , 'EGE ÜNİVERSİTESİ' , 'İzmir' , 'Devlet' , 'http://www.ege.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 60 , 'ERCİYES ÜNİVERSİTESİ' , 'Kayseri' , 'Devlet' , 'http://www.erciyes.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 61 , 'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ' , 'Erzincan' , 'Devlet' , 'http://www.erzincan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 62 , 'ERZURUM TEKNİK ÜNİVERSİTESİ' , 'Erzurum' , 'Devlet' , 'http://www.erzurum.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 63 , 'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ' , 'Eskişehir' , 'Devlet' , 'http://www.ogu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 64 , 'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ' , 'Eskişehir' , 'Devlet' , 'https://www.eskisehir.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 65 , 'FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.fsm.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 66 , 'FENERBAHÇE ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.fbu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 67 , 'FIRAT ÜNİVERSİTESİ' , 'Elazığ' , 'Devlet' , 'http://www.firat.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 68 , 'GALATASARAY ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.gsu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 69 , 'GAZİ ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://gazi.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 70 , 'GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ' , 'Gaziantep' , 'Devlet' , 'http://www.gibtu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 71 , 'GAZİANTEP ÜNİVERSİTESİ' , 'Gaziantep' , 'Devlet' , 'http://www.gantep.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 72 , 'GEBZE TEKNİK ÜNİVERSİTESİ' , 'Kocaeli' , 'Devlet' , 'www.gtu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 73 , 'GİRESUN ÜNİVERSİTESİ' , 'Giresun' , 'Devlet' , 'http://www.giresun.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 74 , 'GÜMÜŞHANE ÜNİVERSİTESİ' , 'Gümüşhane' , 'Devlet' , 'http://www.gumushane.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 75 , 'HACETTEPE ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://hacettepe.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 76 , 'HAKKARİ ÜNİVERSİTESİ' , 'Hakkari' , 'Devlet' , 'www.hakkari.edu.tr / www.hu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 77 , 'HALİÇ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.halic.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 78 , 'HARRAN ÜNİVERSİTESİ' , 'Şanlıurfa' , 'Devlet' , 'http://www.harran.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 79 , 'HASAN KALYONCU ÜNİVERSİTESİ' , 'Gaziantep' , 'Vakıf' , 'www.hku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 80 , 'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ' , 'Hatay' , 'Devlet' , 'http://www.mku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 81 , 'HİTİT ÜNİVERSİTESİ' , 'Çorum' , 'Devlet' , 'http://www.hitit.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 82 , 'IĞDIR ÜNİVERSİTESİ' , 'Iğdır' , 'Devlet' , 'http://www.igdir.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 83 , 'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ' , 'Isparta' , 'Devlet' , 'https://isparta.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 84 , 'IŞIK ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.isikun.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 85 , 'İBN HALDUN ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.ihu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 86 , 'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.bilkent.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 87 , 'İNÖNÜ ÜNİVERSİTESİ' , 'Malatya' , 'Devlet' , 'http://www.inonu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 88 , 'İSKENDERUN TEKNİK ÜNİVERSİTESİ' , 'Hatay' , 'Devlet' , 'www.iste.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 89 , 'İSTANBUL 29 MAYIS ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.29mayis.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 90 , 'İSTANBUL AREL ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.arel.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 91 , 'İSTANBUL ATLAS ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.atlas.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 92 , 'İSTANBUL AYDIN ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.aydin.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 93 , 'İSTANBUL BEYKENT ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.beykent.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 94 , 'İSTANBUL BİLGİ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.bilgi.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 95 , 'İSTANBUL ESENYURT ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.esenyurt.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 96 , 'İSTANBUL GALATA ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.galata.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 97 , 'İSTANBUL GEDİK ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.gedik.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 98 , 'İSTANBUL GELİŞİM ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.gelisim.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 99 , 'İSTANBUL KENT ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.kent.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 100 , 'İSTANBUL KÜLTÜR ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.iku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 101 , 'İSTANBUL MEDENİYET ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.medeniyet.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 102 , 'İSTANBUL MEDİPOL ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.medipol.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 103 , 'İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.nisantasi.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 104 , 'İSTANBUL OKAN ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.okan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 105 , 'İSTANBUL RUMELİ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.rumeli.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 106 , 'İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.izu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 107 , 'İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU' , 'İstanbul' , 'Vakıf' , 'www.issb.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 108 , 'İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.istun.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 109 , 'İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU' , 'İstanbul' , 'Vakıf' , 'www.sisli.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 110 , 'İSTANBUL TEKNİK ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.itu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 111 , 'İSTANBUL TİCARET ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.ticaret.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 112 , 'İSTANBUL TOPKAPI ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.topkapi.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 113 , 'İSTANBUL ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.istanbul.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 114 , 'İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA' , 'İstanbul' , 'Devlet' , 'https://iuc.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 115 , 'İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.yeniyuzyil.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 116 , 'İSTİNYE ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.istinye.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 117 , 'İZMİR BAKIRÇAY ÜNİVERSİTESİ' , 'İzmir' , 'Devlet' , 'bakircay.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 118 , 'İZMİR DEMOKRASİ ÜNİVERSİTESİ' , 'İzmir' , 'Devlet' , 'http://www.idu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 119 , 'İZMİR EKONOMİ ÜNİVERSİTESİ' , 'İzmir' , 'Vakıf' , 'www.ieu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 120 , 'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ' , 'İzmir' , 'Devlet' , 'http://www.ikc.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 121 , 'İZMİR KAVRAM MESLEK YÜKSEKOKULU' , 'İzmir' , 'Vakıf' , 'www.kavram.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 122 , 'İZMİR TINAZTEPE ÜNİVERSİTESİ' , 'İzmir' , 'Vakıf' , 'www.tinaztepe.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 123 , 'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ' , 'İzmir' , 'Devlet' , 'http://www.iyte.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 124 , 'KADİR HAS ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.khas.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 125 , 'KAFKAS ÜNİVERSİTESİ' , 'Kars' , 'Devlet' , 'http://www.kafkas.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 126 , 'KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ' , 'Kahramanmaraş' , 'Devlet' , 'www.istiklal.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 127 , 'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ' , 'Kahramanmaraş' , 'Devlet' , 'www.ksu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 128 , 'KAPADOKYA ÜNİVERSİTESİ' , 'Nevşehir' , 'Vakıf' , 'www.kapadokya.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 129 , 'KARABÜK ÜNİVERSİTESİ' , 'Karabük' , 'Devlet' , 'http://www.karabuk.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 130 , 'KARADENİZ TEKNİK ÜNİVERSİTESİ' , 'Trabzon' , 'Devlet' , 'http://www.ktu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 131 , 'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ' , 'Karaman' , 'Devlet' , 'http://www.kmu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 132 , 'KASTAMONU ÜNİVERSİTESİ' , 'Kastamonu' , 'Devlet' , 'http://www.kastamonu.edu.tr/index.php/tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 133 , 'KAYSERİ ÜNİVERSİTESİ' , 'Kayseri' , 'Devlet' , 'http://www.kayseri.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 134 , 'KIRIKKALE ÜNİVERSİTESİ' , 'Kırıkkale' , 'Devlet' , 'http://kku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 135 , 'KIRKLARELİ ÜNİVERSİTESİ' , 'Kırklareli' , 'Devlet' , 'http://www.klu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 136 , 'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ' , 'Kırşehir' , 'Devlet' , 'www.ahievran.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 137 , 'KİLİS 7 ARALIK ÜNİVERSİTESİ' , 'Kilis' , 'Devlet' , 'www.kilis.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 138 , 'KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ' , 'Kocaeli' , 'Vakıf' , 'www.kocaelisaglik.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 139 , 'KOCAELİ ÜNİVERSİTESİ' , 'Kocaeli' , 'Devlet' , 'http://www.kocaeli.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 140 , 'KOÇ ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.ku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 141 , 'KONYA GIDA VE TARIM ÜNİVERSİTESİ' , 'Konya' , 'Vakıf' , 'http://www.gidatarim.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 142 , 'KONYA TEKNİK ÜNİVERSİTESİ' , 'Konya' , 'Devlet' , 'http://www.ktun.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 143 , 'KTO KARATAY ÜNİVERSİTESİ' , 'Konya' , 'Vakıf' , 'http://www.karatay.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 144 , 'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ' , 'Kütahya' , 'Devlet' , 'http://dpu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 145 , 'KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ' , 'Kütahya' , 'Devlet' , 'http://www.ksbu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 146 , 'LOKMAN HEKİM ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.lokmanhekim.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 147 , 'MALATYA TURGUT ÖZAL ÜNİVERSİTESİ' , 'Malatya' , 'Devlet' , 'www.ozal.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 148 , 'MALTEPE ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.maltepe.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 149 , 'MANİSA CELÂL BAYAR ÜNİVERSİTESİ' , 'Manisa' , 'Devlet' , 'www.cbu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 150 , 'MARDİN ARTUKLU ÜNİVERSİTESİ' , 'Mardin' , 'Devlet' , 'http://www.artuklu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 151 , 'MARMARA ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.marmara.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 152 , 'MEF ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.mef.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 153 , 'MERSİN ÜNİVERSİTESİ' , 'Mersin' , 'Devlet' , 'http://www.mersin.edu.tr/idari/genel-sekreterlik' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 154 , 'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'https://www.msgsu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 155 , 'MUDANYA ÜNİVERSİTESİ' , 'Bursa' , 'Vakıf' , 'https://mudanya.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 156 , 'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ' , 'Muğla' , 'Devlet' , 'http://www.mu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 157 , 'MUNZUR ÜNİVERSİTESİ' , 'Tunceli' , 'Devlet' , 'www.munzur.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 158 , 'MUŞ ALPARSLAN ÜNİVERSİTESİ' , 'Muş' , 'Devlet' , 'www.alparslan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 159 , 'NECMETTİN ERBAKAN ÜNİVERSİTESİ' , 'Konya' , 'Devlet' , 'http://www.erbakan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 160 , 'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ' , 'Nevşehir' , 'Devlet' , 'http://www.nevsehir.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 161 , 'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ' , 'Niğde' , 'Devlet' , 'http://www.ohu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 162 , 'NUH NACİ YAZGAN ÜNİVERSİTESİ' , 'Kayseri' , 'Vakıf' , 'http://www.nny.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 163 , 'ONDOKUZ MAYIS ÜNİVERSİTESİ' , 'Samsun' , 'Devlet' , 'http://www.omu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 164 , 'ORDU ÜNİVERSİTESİ' , 'Ordu' , 'Devlet' , 'http://www.odu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 165 , 'ORTA DOĞU TEKNİK ÜNİVERSİTESİ' , 'Ankara' , 'Devlet' , 'http://www.metu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 166 , 'OSMANİYE KORKUT ATA ÜNİVERSİTESİ' , 'Osmaniye' , 'Devlet' , 'http://www.osmaniye.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 167 , 'OSTİM TEKNİK ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.ostimteknik.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 168 , 'ÖZYEĞİN ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'www.ozyegin.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 169 , 'PAMUKKALE ÜNİVERSİTESİ' , 'Denizli' , 'Devlet' , 'http://www.pau.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 170 , 'PİRİ REİS ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.pirireis.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 171 , 'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ' , 'Rize' , 'Devlet' , 'erdogan.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 172 , 'SABANCI ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.sabanciuniv.edu' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 173 , 'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.sbu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 174 , 'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ' , 'Sakarya' , 'Devlet' , 'www.subu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 175 , 'SAKARYA ÜNİVERSİTESİ' , 'Sakarya' , 'Devlet' , 'http://www.sakarya.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 176 , 'SAMSUN ÜNİVERSİTESİ' , 'Samsun' , 'Devlet' , 'www.samsun.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 177 , 'SANKO ÜNİVERSİTESİ' , 'Gaziantep' , 'Vakıf' , 'http://www.sanko.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 178 , 'SELÇUK ÜNİVERSİTESİ' , 'Konya' , 'Devlet' , 'http://www.selcuk.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 179 , 'SİİRT ÜNİVERSİTESİ' , 'Siirt' , 'Devlet' , 'http://siirt.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 180 , 'SİNOP ÜNİVERSİTESİ' , 'Sinop' , 'Devlet' , 'http://www.sinop.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 181 , 'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ' , 'Sivas' , 'Devlet' , 'http://www.sivas.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 182 , 'SİVAS CUMHURİYET ÜNİVERSİTESİ' , 'Sivas' , 'Devlet' , 'http://www.cumhuriyet.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 183 , 'SÜLEYMAN DEMİREL ÜNİVERSİTESİ' , 'Isparta' , 'Devlet' , 'http://www.sdu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 184 , 'ŞIRNAK ÜNİVERSİTESİ' , 'Şırnak' , 'Devlet' , 'http://www.sirnak.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 185 , 'TARSUS ÜNİVERSİTESİ' , 'Mersin' , 'Devlet' , 'www.tarsus.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 186 , 'TED ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.tedu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 187 , 'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ' , 'Tekirdağ' , 'Devlet' , 'http://www.nku.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 188 , 'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'www.etu.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 189 , 'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ' , 'Tokat' , 'Devlet' , 'www.gop.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 190 , 'TOROS ÜNİVERSİTESİ' , 'Mersin' , 'Vakıf' , 'www.toros.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 191 , 'TRABZON ÜNİVERSİTESİ' , 'Trabzon' , 'Devlet' , 'www.trabzon.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 192 , 'TRAKYA ÜNİVERSİTESİ' , 'Edirne' , 'Devlet' , 'http://www.trakya.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 193 , 'TÜRK HAVA KURUMU ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.thk.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 194 , 'TÜRK-ALMAN ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.tau.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 195 , 'UFUK ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'http://www.ufuk.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 196 , 'UŞAK ÜNİVERSİTESİ' , 'Uşak' , 'Devlet' , 'http://www.usak.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 197 , 'ÜSKÜDAR ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.uskudar.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 198 , 'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ' , 'Van' , 'Devlet' , 'http://www.yyu.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 199 , 'YALOVA ÜNİVERSİTESİ' , 'Yalova' , 'Devlet' , 'http://www.yalova.edu.tr/rektorluk' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 200 , 'YAŞAR ÜNİVERSİTESİ' , 'İzmir' , 'Vakıf' , 'http://www.yasar.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 201 , 'YEDİTEPE ÜNİVERSİTESİ' , 'İstanbul' , 'Vakıf' , 'http://www.yeditepe.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 202 , 'YILDIZ TEKNİK ÜNİVERSİTESİ' , 'İstanbul' , 'Devlet' , 'http://www.yildiz.edu.tr' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 203 , 'YOZGAT BOZOK ÜNİVERSİTESİ' , 'Yozgat' , 'Devlet' , 'http://www.bozok.edu.tr/' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 204 , 'YÜKSEK İHTİSAS ÜNİVERSİTESİ' , 'Ankara' , 'Vakıf' , 'Yüksek İhtisas Üniversitesi' );
INSERT INTO uni (id,name,location,type,url) VALUES  ( 205 , 'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ' , 'Zonguldak' , 'Devlet' , 'https://www.beun.edu.tr' );

